<#
================================================================================
  mitigation_gate.ps1 — Angerona SOAR containment gate.

  Applies the autonomous, review-gated network-containment playbooks generated by
  the playbook tuner (playbooks\dynamic_block_<tid>.ps1) when a standard
  Kill Process fails to neutralize an execution vector (decoupled WMI hook,
  process hollowing, etc.).

  Every rule these playbooks create is tagged group 'Angerona-SOAR' and always
  leaves loopback (Ollama :11434 / IPC) reachable. One-line rollback:
      Remove-NetFirewallRule -Group 'Angerona-SOAR'

  Dynamic playbook references are appended below by playbook_tuner._register_in_gate.
================================================================================
#>
$ErrorActionPreference = 'SilentlyContinue'
Write-Host "[*] Angerona mitigation gate — applying dynamic containment playbooks..." -ForegroundColor Cyan

# Loopback must always stay open so local Ollama triage + the IPC channel survive
# any containment applied below.
New-NetFirewallRule -DisplayName 'Angerona-SOAR-Loopback-Guard' -Group 'Angerona-SOAR' `
    -Direction Outbound -RemoteAddress 127.0.0.1 -Action Allow -ErrorAction SilentlyContinue | Out-Null

# ── dynamic playbooks (auto-appended by playbook_tuner) ─────────────────────
. "$PSScriptRoot\playbooks\dynamic_block_T1547.001.ps1"   # T1547.001
. "$PSScriptRoot\playbooks\dynamic_block_T1070.ps1"   # T1070
. "$PSScriptRoot\playbooks\dynamic_block_T1546.003.ps1"   # T1546.003
. "$PSScriptRoot\playbooks\dynamic_block_T1003.ps1"   # T1003
