"""Generate one exact wheel lock and artifact manifest for a POSIX target.

This is a maintainer tool.  It performs no network access and rejects missing,
duplicate, or unreviewed wheelhouse contents so a lock cannot silently omit a
dependency or bless an extra artifact.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path

from packaging.utils import canonicalize_name, parse_wheel_filename


_PIN = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s#]+)$")


@dataclass(frozen=True)
class Artifact:
    name: str
    version: str
    filename: str
    size: int
    sha256: str


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _pins(path: Path) -> list[tuple[str, str]]:
    result: list[tuple[str, str]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = _PIN.fullmatch(line)
        if match is None:
            raise ValueError(f"constraint is not an exact pin: {raw!r}")
        result.append(match.groups())
    return result


def select_artifacts(constraints: Path, wheelhouse: Path) -> list[Artifact]:
    wheels: dict[tuple[str, str], list[Path]] = {}
    all_wheels: set[Path] = set()
    for path in sorted(wheelhouse.iterdir()):
        if path.suffix != ".whl":
            raise ValueError(f"non-wheel artifact in wheelhouse: {path.name}")
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"wheel must be a regular non-symlink file: {path.name}")
        name, version, _build, _tags = parse_wheel_filename(path.name)
        wheels.setdefault((canonicalize_name(name), str(version)), []).append(path)
        all_wheels.add(path)

    selected: list[Artifact] = []
    selected_paths: set[Path] = set()
    for display_name, version in _pins(constraints):
        matches = wheels.get((canonicalize_name(display_name), version), [])
        if len(matches) != 1:
            raise ValueError(
                f"{display_name}=={version}: expected exactly one selected wheel, "
                f"found {len(matches)}"
            )
        path = matches[0]
        selected_paths.add(path)
        selected.append(
            Artifact(
                name=display_name,
                version=version,
                filename=path.name,
                size=path.stat().st_size,
                sha256=_sha256(path),
            )
        )

    extras = sorted(path.name for path in all_wheels - selected_paths)
    if extras:
        raise ValueError(f"unreviewed extra wheel(s): {', '.join(extras)}")
    return selected


def build_lock(target: str, artifacts: list[Artifact]) -> str:
    output = [
        "# Generated by tools/build_posix_release_locks.py.",
        f"# Target: CPython 3.12, {target}. Refresh only after review.",
        "--only-binary=:all:",
        "",
    ]
    for item in artifacts:
        output.extend(
            (
                f"{item.name}=={item.version} \\",
                f"    --hash=sha256:{item.sha256}",
                "",
            )
        )
    return "\n".join(output).rstrip() + "\n"


def build_manifest(target: str, artifacts: list[Artifact]) -> str:
    payload = {
        "schema": 1,
        "target": target,
        "python": "cp312",
        "artifacts": [
            {
                "name": item.name,
                "version": item.version,
                "filename": item.filename,
                "size": item.size,
                "sha256": item.sha256,
            }
            for item in artifacts
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", required=True)
    parser.add_argument("--constraints", type=Path, default=Path("constraints-posix-release.txt"))
    parser.add_argument("--wheelhouse", type=Path, required=True)
    parser.add_argument("--lock", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    args = parser.parse_args()
    artifacts = select_artifacts(args.constraints, args.wheelhouse)
    args.lock.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.lock.write_text(build_lock(args.target, artifacts), encoding="utf-8", newline="\n")
    args.manifest.write_text(
        build_manifest(args.target, artifacts), encoding="utf-8", newline="\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
