"""Build the Windows/Python 3.12 release hash lock from audited wheels.

The input wheelhouse must be populated with exactly the artifacts selected for
the release runner. This tool performs no network access and fails closed when a
constraint has no matching wheel or more than one matching artifact.
"""
from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path

from packaging.utils import canonicalize_name, parse_wheel_filename


_PIN = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s#]+)$")


def build_lock(constraints: Path, wheelhouse: Path) -> str:
    wheels: dict[tuple[str, str], list[Path]] = {}
    for path in sorted(wheelhouse.glob("*.whl")):
        name, version, _build, _tags = parse_wheel_filename(path.name)
        wheels.setdefault((canonicalize_name(name), str(version)), []).append(path)

    output = [
        "# Generated by tools/build_release_hash_lock.py.",
        "# Target: CPython 3.12, Windows x86-64. Refresh only after review.",
        "--only-binary=:all:",
        "",
    ]
    for raw in constraints.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = _PIN.fullmatch(line)
        if match is None:
            raise ValueError(f"constraint is not an exact pin: {raw!r}")
        name, version = match.groups()
        matches = wheels.get((canonicalize_name(name), version), [])
        if len(matches) != 1:
            raise ValueError(
                f"{name}=={version}: expected exactly one selected wheel, "
                f"found {len(matches)}"
            )
        digest = hashlib.sha256(matches[0].read_bytes()).hexdigest()
        output.extend((f"{name}=={version} \\", f"    --hash=sha256:{digest}", ""))
    return "\n".join(output).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--constraints", type=Path, default=Path("constraints-release.txt"))
    parser.add_argument("--wheelhouse", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("requirements-release-hashed.txt"))
    args = parser.parse_args()
    args.output.write_text(
        build_lock(args.constraints, args.wheelhouse), encoding="utf-8", newline="\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
